modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/incubation/issues"
license = "https://github.com/team-abnormals/incubation/blob/main/LICENSE.txt"

[[mods]]
    modId = "incubation"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "incubation:hay_nest"
    configBackground = "minecraft:textures/block/hay_block_side.png"
    authors = "Team Abnormals"
    credits = "bageldotjpg"
    displayURL = "https://www.teamabnormals.com/mods/incubation"
    displayName = "Incubation"
    description = '''
    Lays down a dozen of egg-related features, including fried eggs, scrambled eggs, bird nests, and more!
    '''

[[dependencies.incubation]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20.1,1.21)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.incubation]]
    modId = "forge"
    mandatory = true
    versionRange = "[47.1.3,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.incubation]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[7.0.1,)"
    ordering = "AFTER"
    side = "BOTH"